# Site settings
title: Utvecklarbloggen
email: itutvecklare@ub.gu.se
description: > # this means to ignore newlines until "baseurl:"
  Ett anteckningsblock för utvecklarteamet vid Göteborgs Universitetsbibliotek. Här finns tips och tricks, länkar och annat som vi behöver ha snabb tillgång till.

baseurl: "/our-blog" # the subpath of your site, e.g. /blog/
url: "http://ub.gu.se" # the base hostname & protocol for your site
github_username:  ub-digit

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'bower.json', 'bower_components']


